
channels:
- conda-forge
- anaconda
dependencies:
- python=3.7
- scikit-learn
- pandas
- numpy
- pip:
  - azureml-defaults 
  - pingouin
  - lightgbm
  - joblib  
  - Boruta
  - inference-schema
  - azureml-interpret